### ISSUE TITLE
OAuth2 Authentication fails in a proxied environment. 

### ISSUE THREAD

**Issue by inktomi** [googleapis/google-auth-library-java#900] opened 2022-03-29 21:29 UTC
#### Environment details
I'm using [Flank](https://github.com/Flank/flank/issues/2235) which in turn uses this library to communicate with Firebase Test Lab. 

When running behind a proxy, I get an authentication error about trying to read "seconds". 

#### Steps to reproduce

  1. Download Flank, and attempt to run it in a proxied environment. 

#### Stack trace
```
Warning: Failed to make bucket for ...our-bucket...
Cause: java.lang.NullPointerException: Cannot read field "seconds" because "otherDuration" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot read field "seconds" because "otherDuration" is null
        at ftl.client.google.IosCatalog.iosDeviceCatalog(IosCatalog.kt:58)
        at ftl.client.google.IosCatalog.getModels(IosCatalog.kt:21)
        at ftl.client.google.AndroidCatalog.isVirtualDevice(AndroidCatalog.kt:51)
        at ftl.args.PrepareAndroidCommonConfigKt.resolveDeviceType(PrepareAndroidCommonConfig.kt:14)
        at ftl.args.PrepareAndroidCommonConfigKt.prepareAndroidCommonConfig(PrepareAndroidCommonConfig.kt:10)
        at ftl.args.CreateAndroidArgsKt.createAndroidArgs$default(CreateAndroidArgs.kt:15)
        at ftl.domain.RunTestAndroidKt.invoke(RunTestAndroid.kt:46)
        at ftl.presentation.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:58)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at ftl.Main$main$1.invoke(Main.kt:12)
        at ftl.Main$main$1.invoke(Main.kt:10)
        at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:28)
        at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:17)
        at ftl.Main.main(Main.kt:10)
Caused by: java.lang.NullPointerException: Cannot read field "seconds" because "otherDuration" is null
        at java.base/java.time.Duration.compareTo(Duration.java:1411)
        at com.google.auth.oauth2.OAuth2Credentials.getState(OAuth2Credentials.java:342)
        at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:207)
        at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:170)
        at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
        at ftl.http.HttpTimeoutIncrease.initialize(HttpTimeoutIncrease.kt:10)
        at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:404)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
        at ftl.http.ExecuteWithRetryKt$executeWithRetry$$inlined$withRetry$1.invokeSuspend(ExecuteWithRetry.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at ftl.http.ExecuteWithRetryKt.executeWithRetry(ExecuteWithRetry.kt:52)
        at ftl.client.google.IosCatalog.iosDeviceCatalog(IosCatalog.kt:53)
        ... 20 more
```

I'm happy to gather more information if it would be helpful, or to try suggested fixes.

**Comment by TimurSadykov** [comment] 2022-05-06 03:16
Hi @inktomi 

By looking into the code I see that the error could happen if Credential is instantiated with incorrect value in the first place, where expiration time == null. But where it is coming from? 

The fact that there is an error and happens in the library is not a bug by itself. It depends on an input. Proxied environments are very common as well.

Could you please help us to investigate further or ask Flack people to isolate the issue? What would help is to know what is the exact input that causes the error and if it is valid. 

Thanks!

**Comment by TimurSadykov** [comment] 2022-07-19 08:10
Closing until more info provided

**Closed by TimurSadykov** 2022-07-19 08:10 UTC
Labels: status: investigating
