### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by elharo** [googleapis/google-auth-library-java#183] opened 2018-08-31 20:33 UTC
What, if anything, is standing in the way of a GA 1.0 release? 

Specifically I would like to remove this statement from the README:

"Note: This client is a work-in-progress, and may occasionally make backwards-incompatible changes."

What, if anything, still needs to be done before this can happen? This library is on the critical path for many other Google products. We need to finish it and commit to an API clients can rely on.

**Comment by garrettjonesgoogle** [comment] 2018-09-21 17:00
Relevant best practice: https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-8.md "Advance widely used functionality to a stable version"

**Comment by elharo** [comment] 2018-10-19 18:28
You can close this as a dupe of 101. I don't have permissions to do so.

**Comment by garrettjonesgoogle** [comment] 2018-10-19 18:33
Duplicate of #101

**Closed by garrettjonesgoogle** 2018-10-19 18:33 UTC
Labels: duplicate, status: duplicate, type: process
